services:
  postgres:
    image: postgres:12
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soundify
    volumes:
      - soundify_db_data:/var/lib/postgresql/data

volumes:
  soundify_db_data:
    driver: local
